# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X5yZWvsfS7udTaqcxP9yCxQUVgUmuwBY
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df=pd.read_csv("/content/tips.csv")

df

df.info()

df.describe()

df.shape

df.isnull()

print(df["tip"].mean())

print(df["tip"].median())

print(df["tip"].mode())

print(df["tip"].std())

df=df.drop_duplicates()

df

print (df[["total_bill","tip"]].describe())

df[["total_bill","tip"]].plot(kind="box")
plt.title("box for total bill and tip")
plt.ylabel("amount")
plt.show

print(df[["total_bill","tip"]].skew())

!pip install feature-engine

from feature_engine.outliers import Winsorizer

a = Winsorizer(capping_method= 'iqr',tail= 'both',fold = 1.5,variables= ['total_bill'])

a=Winsorizer(capping_method= 'iqr',tail= 'both',fold = 1.5,variables= ['tip'])

a=Winsorizer(capping_method= 'iqr',tail= 'both',fold = 1.5,variables= ['size'])

df.plot(kind='box',subplots =True ,sharey = False,figsize = (10,6))
plt.subplots_adjust(wspace=0.75)

